gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  showIcons: true
  branchColors:
    'main': 'blue'
    'master': 'blue'
    'feature': 'green'
    'release': 'yellow'
    'hotfix': 'red'
