git:
  paging:
    colorArg: always
    pager: delta --paging=never
gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  showIcons: false
  branchColors:
    'main': 'blue'
    'master': 'blue'
    'feature': 'green'
    'release': 'yellow'
    'hotfix': 'red'
