git:
  paging:
    colorArg: always
    pager: delta --paging=never
gui:
  showIcons: true
  nerdFontsVersion: "3"
  spinner:
    frames: ["🌑 ", "🌒 ", "🌓 ", "🌔 ", "🌕 ", "🌖 ", "🌗 ", "🌘 "]
    rate: 80
  theme:
    searchingActiveBorderColor:
      - "#fab387"
      - "bold"
    optionsTextColor:
      - "#89b4fa"
    inactiveBorderColor:
      - "#89b4fa"
    defaultFgColor:
      - "#cdd6f4"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    cherryPickedCommitBgColor:
      - "#f2cdcd"
    activeBorderColor:
      - "#fab387"
      - "bold"
    unstagedChangesColor:
      - "#f38ba8"
    selectedLineBgColor:
      - "#45475a"
  branchColors:
    "main": "blue"
    "master": "blue"
    "feature": "green"
    "release": "yellow"
    "hotfix": "red"
