# first: set -Ux TEALDEER_CONFIG_DIR "$HOME/.config/tealdeer"
[display]
compact = true

[updates]
auto_update = true

[style.description]
foreground = "magenta"

[style.command_name]
foreground = "red"

[style.example_text]
foreground = "green"

[style.example_code]
foreground = "blue"

[style.example_variable]
foreground = "cyan"
underline = true
