theme = "tokyonight"

[editor]
line-number = "relative"
mouse = false
rulers = [80]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w"
C-o = ":open ~/.config/helix/config.toml"

[keys.insert]
j = { k = "normal_mode" }