command_timeout = 3000
[directory]
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "

[time]
format = "[$time]($style) "
disabled = false

[gcloud]
disabled = true

[shell]
fish_indicator = "󰈺 "
bash_indicator = " "
style = "cyan bold"
disabled = false

[aws.region_aliases]
us-east-1 = 'Virgina'
us-west-2 = 'Oregon'
