command_timeout = 2000

# Don't print a new line at the start of the prompt
add_newline = true

# makes prompt a single line
# [line_break]
# disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
min_time = 3_000                    # Show command duration over 10,000 milliseconds (= 10 sec)
format = "took [$duration]($style)"

# These symbols will only show when battery levels are 20% or less
[battery]
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]] # "bold red" style when capacity is between 0% and 20%
threshold = 20
style = "bold red"

# Clear visibility for exit codes
[status]
style = "bg:red"
symbol = "💣"
format = '[\[$symbol$status\]]($style) '
map_symbol = true
pipestatus = true
disabled = false

[character]
error_symbol = "[X](bold red) "

# Git branch
[git_branch]
symbol = "🌱 "

# Git commit hash
[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

# Git state
[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

# Git status icons
[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

[time]
disabled = false
# format = '🕙 $time($style) '
# time_format = "%T"
# use_12hr = true
# utc_time_offset = "-5"
# time_range = "10:00:00-14:00:00"
