command_timeout = 3000

[character]
error_symbol = "[✗](bold red)"

[directory]
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "

[time]
format = "[$time]($style) "
disabled = false

[gcloud]
disabled = true

[shell]
fish_indicator = "󰈺 "
bash_indicator = " "
style = "cyan bold"
disabled = false

[aws]
symbol = "󰸏 "

[aws.region_aliases]
us-east-1 = 'Virgina'
us-west-2 = 'Oregon'

[custom.chezmoi]
detect_files = [".chezmoiroot"]
# This makes the prompt too slow, nice in concept though
# when = "ps aux | grep chezmoi | grep -v grep"
symbol = "🥖"
style = "green"
format = "[$symbol]($style)"
