gui:
  theme:
    activeBorderColor:
      - "#fab387"
      - "bold"
    inactiveBorderColor:
      - "#89b4fa"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#45475a"
    defaultFgColor:
      - "#cdd6f4"
